apiVersion: v1
kind: Secret
metadata:
  name: poker-agents-secrets
type: Opaque
data:
  timer-key: {{ .Values.timerAgent.key | b64enc }}
  openrouter-api-key: {{ .Values.openRouter.apiKey | b64enc }}
  {{- range $i, $agent := .Values.pokerAgents }}
  agent{{ add $i 1 }}-key: {{ $agent.key | b64enc }}
  {{- end }}